In [ ]:
import numpy as np

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_matrix)

In [ ]:
print(np.array(my_matrix))

In [ ]:
print(np.arange(0,11,2))

In [ ]:
print(np.zeros(3))

In [ ]:
print(np.zeros((2,3)))

In [ ]:
print(np.linspace(0,10,5))

In [ ]:
print(np.linspace(0,5,10))

In [ ]:
np.eye(4)

In [ ]:
print(np.random.rand(2,2))

In [ ]:
print(np.random.randn(2,2))

In [ ]:
print(np.random.randint(1,50,5))

In [ ]:
arr = np.arange(25)

In [ ]:
print(arr)

In [ ]:
print(arr.reshape(5,5))

In [ ]:
print(arr.dtype)

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [ ]:
arr_2d

In [ ]:
arr_2d[:2,1:]

In [ ]:
sum(arr_2d)

In [ ]:
arr_2d.sum()

In [ ]:
arr =np.array([[1, 2, 3],
               [4, 5, 6]]) 

In [ ]:
arr.sum(axis=0)

In [ ]:
arr.sum(axis=1)

In [ ]:
a =np.array([[1, 2, 3],
               [4, 5, 6]]) 

In [ ]:
b =np.array([[1, 2],
              [3, 4],
              [5, 6]]) 

In [ ]:
a.dot(b)

In [ ]:
a.transpose()

In [ ]:
import numpy as np

In [ ]:
dir(np)

In [ ]:
len(dir(np))

In [ ]:
a =np.array([[1, 2, 3],
               [4, 5, 6]]) 

In [ ]:
b =np.array([[1, 2, 3],
               [4, 5, 6]]) 

In [ ]:
np.cross(a,b)

In [ ]:
a =np.array([[7, 2, 9],
               [5, 1, 3]]) 

In [ ]:
np.sort(a)

In [ ]:
a

In [ ]:
np.sort(a, kind='mergesort')

In [ ]:
%time np.sort(a, kind='mergesort')

In [ ]:
%%time
np.sort(a, kind='mergesort')

# Numpy | Iterating Over Array

In [ ]:
import numpy as np
 
# creating an array using arrange 
# method
a = np.arange(12)
 
# shape array with 3 rows and 
# 4 columns
a = a.reshape(3,4)
 
print('Original array is:')
print(a)
print()
 
print('Modified array is:')
 
# iterating  an array
for x in np.nditer(a):
    print(x)

# Controlling Iteration Order:

# C order

In [ ]:
import numpy as np 
 
# creating an array using arrange 
# method
a = np.arange(12) 
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('Original array is:') 
print(a)
print()  
 
print('Modified array in C-style order:')
 
# iterating an array in a given
# order  
for x in np.nditer(a, order = 'C'): 
    print(x)

# F order

In [ ]:
import numpy as np 
 
# creating an array using arrange 
# method
a = np.arange(0,60,5) 
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('Original array is:') 
print(a)
print()  
 
print('Modified array in F-style order:')
 
# iterating an array in a given
# order   
for x in np.nditer(a, order = 'F'): 
    print(x)

# Modifying array values

In [ ]:
import numpy as np
 
# creating an array using arrange 
# method
a = np.arange(12)
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4)
print('Original array is:')
print(a)
print()
 
# modifying array values
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 5*x
print('Modified array is:')
print(a)


# Broadcasting Iteratioins

In [ ]:
import numpy as np
 
# creating an array using arrange 
# method 
a = np.arange(12)
 
 # shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('First array is:') 
print(a)
print()  
 
# Creating second array using 
# array method
print('Second array is:') 
b = np.array([5, 6, 7, 8], dtype = int) 
print(b)  
print() 
 
for x,y in np.nditer([a,b]): 
    print("%d:%d" % (x,y))

# Take User Input & Store in Numpy 1 D array : 

# Method 1 : build a normal list and convert it to a numpy array afterwards

In [ ]:
import numpy

my_array = []
a = int(input("Size of array:"))
for i in range(a):
    my_array.append(float(input("Element:")))
my_array = numpy.array(my_array)
print(numpy.floor(my_array))

# Method 2 : initialise a list of length 'a' and then can replace its element with input elements

In [ ]:
import numpy
a=int(input("Size of array:"))

my_array = numpy.empty(a)
for i in range(len(my_array)):
    x=float(input("Element:"))
    my_array[i]=x
print(numpy.floor(my_array))

# NumPy Matrix Multiplication with np.matmul(

In [3]:
import numpy as np
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 

np.matmul(h, i)

array([[19, 22],
       [43, 50]])

# Finding Determinant

In [7]:
import numpy as np
h = [[1,1],[3,4]] 
i = [[5,5],[7,8]] 
print(np.linalg.det(h))
print(np.linalg.det(i))

0.9999999999999998
4.999999999999994


# Taking input from user & performing Numpy Matrix Multipicatioin using Dot  Operator

In [8]:
# Note: We can either write
# np.dot(a,b)
# a.dot(b)


# Import numpy 
import numpy as np
 
def printMatrix(a):
    
    # Printing matrix
    for i in range(0,len(a)):
        for j in range(0,len(a[0])):
            print(a[i][j],end = " ")
        print()
    
    
 
def main():
    
    # Taking rows and columns of a 
    m = int(input("Enter rows in a : "))
    n = int(input("Enter columns in a : "))
    
    # Taking rows and columns of b
    p = int(input("Enter rows in b : "))
    q = int(input("Enter columns in b : "))
    
    # Checking necessary condition for matrix multiplication
    if n!= p:
        print("Number of columns in b must be equal to rows in b")
        exit()
    
    # Initializing a and b list
    a = [ [0 for i in range(0,n)] for j in range(0,m) ]
    b = [ [0 for i in range(0,q)] for j in range(0,p) ]
    
    # Taking input list a
    print("Enter matrix a : ")
    for i in range(0,m):
        for j in range(0,n):
            a[i][j] = int(input("Enter element a[" + str(i) + "][" + str(j) + "] : "))
    
    # Taking input list b
    print("Enter matrix b : ")
    for i in range(0,p):
        for j in range(0,q):
            b[i][j] = int(input("Enter element b[" + str(i) + "][" + str(j) + "] : "))
    
    
    # Converting python list in numpy array
    a = np.array(a)
    b = np.array(b)
    
    print("Matrix a :")
    printMatrix(a)
    print()
    
    print("Matrix b : ")
    printMatrix(b)
    print()
    
    # Using dot operator to multiply
    c = a.dot(b)
    
    # Printing Result
    print("Result of a*b : ")
    printMatrix(c)
 
 
main()

Enter rows in a : 2
Enter columns in a : 3
Enter rows in b : 3
Enter columns in b : 2
Enter matrix a : 
Enter element a[0][0] : 2
Enter element a[0][1] : 3
Enter element a[0][2] : 4
Enter element a[1][0] : 1
Enter element a[1][1] : 2
Enter element a[1][2] : 3
Enter matrix b : 
Enter element b[0][0] : 4
Enter element b[0][1] : 5
Enter element b[1][0] : 1
Enter element b[1][1] : 6
Enter element b[2][0] : 9
Enter element b[2][1] : 7
Matrix a :
2 3 4 
1 2 3 

Matrix b : 
4 5 
1 6 
9 7 

Result of a*b : 
47 56 
33 38 


In [9]:

# Import numpy 
import numpy as np
 
def printMatrix(a):
    
    # Printing matrix
    for i in range(0,len(a)):
        for j in range(0,len(a[0])):
            print(a[i][j],end = " ")
        print()
    
    
 
def main():
    
    # Taking rows and columns of a 
    m = int(input("Enter rows in a : "))
    n = int(input("Enter columns in a : "))
    
    # Taking rows and columns of b
    p = int(input("Enter rows in b : "))
    q = int(input("Enter columns in b : "))
    
    # Checking necessary condition for matrix multiplication
    if n!= p:
        print("Number of columns in b must be equal to rows in b")
        exit()
    
    # Initializing a and b list
    a = [ [0 for i in range(0,n)] for j in range(0,m) ]
    b = [ [0 for i in range(0,q)] for j in range(0,p) ]
    
    # Taking input list a
    print("Enter matrix a : ")
    for i in range(0,m):
        for j in range(0,n):
            a[i][j] = int(input("Enter element a[" + str(i) + "][" + str(j) + "] : "))
    
    # Taking input list b
    print("Enter matrix b : ")
    for i in range(0,p):
        for j in range(0,q):
            b[i][j] = int(input("Enter element b[" + str(i) + "][" + str(j) + "] : "))
    
    
    # Converting python list in numpy array
    a = np.array(a)
    b = np.array(b)
    
    print("Matrix a :")
    printMatrix(a)
    print()
    
    print("Matrix b : ")
    printMatrix(b)
    print()
    
    # Using * operator to multiply
    c = np.matrix(a)*np.matrix(b)
    
    # Printing Result
    print("Result of a*b : ")
    printMatrix(c)
 
 
main()

Enter rows in a : 2
Enter columns in a : 3
Enter rows in b : 3
Enter columns in b : 2
Enter matrix a : 
Enter element a[0][0] : 2
Enter element a[0][1] : 3
Enter element a[0][2] : 4
Enter element a[1][0] : 1
Enter element a[1][1] : 2
Enter element a[1][2] : 3
Enter matrix b : 
Enter element b[0][0] : 4
Enter element b[0][1] : 5
Enter element b[1][0] : 1
Enter element b[1][1] : 6
Enter element b[2][0] : 9
Enter element b[2][1] : 7
Matrix a :
2 3 4 
1 2 3 

Matrix b : 
4 5 
1 6 
9 7 

Result of a*b : 
[[47 56]] 
[[33 38]] 


# NumPy Statistical Functions with Example

# Consider the following Array

In [10]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[5.84590697 5.31132962 5.04707243 4.86221171 4.41626211 4.39063585
 4.92517839 4.78450755 5.7410437  5.42243308]


# Example:Statistical function

In [11]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.3906358493121225
5.845906973507198
5.074658141203084
4.986125410037205
0.4764087664496949
